quarkus.http.port=8181
quarkus.http.access-log.enabled=true
quarkus.http.access-log.pattern=common

quarkus.datasource.db-kind = postgresql
quarkus.datasource.username = ${QUARKUS_DATASOURCE_USERNAME:joao}
quarkus.datasource.password = ${QUARKUS_DATASOURCE_PASSWORD:joao}
quarkus.datasource.reactive.url = postgresql://${QUARKUS_DATASOURCE_HOST:localhost}:${QUARKUS_DATASOURCE_PORT:5432}/agencia

# Teremos um conjunto de configurações, e utilizaremos o MicroProfile, um framework baseado no Jakarta EE,
# que vem ganhando notoriedade no mundo open source e em aplicações empresariais e em cloud. Usaremos o SmallWrite,
# que tem sinergia com o MicroProfile. Adicionamos message, referente à mensageria, que neste caso será RabbitMQ,
# pois é o que estamos utilizando no curso. Outgoing significa que a saída é o producer, ou seja, a nossa aplicação é um producer.
# Também haverá um Income, que será a entrada, o Consumer, que será o Audit.
# Mas aqui faremos o Outgoing, que é para onde estamos enviando a mensagem.
#
# Notificações, ou NotificaCoins, é o nome do nosso Channel. O Channel é o canal que abrimos entre a aplicação e o RabbitMQ.
# Quando subirmos a aplicação, veremos que no RabbitMQ haverá esse canal, e automaticamente ele já gera o Exchange com o nome Notificações.
# O Connector será SmallWrite RabbitMQ, que é o padrão.
# O Exchange Type será Direct, ou seja,
# precisamos de um Routing Key para informar ao RabbitMQ para qual fila a mensagem deve ser enviada. Por isso,
# definimos um Default Routing Key, que será Agência Change Status. No RabbitMQ, ao configurar, criaremos essa Routing Key,
# vincularemos à fila, e o Rabbit saberá que deve enviar para aquela fila específica.
mp.messaging.outgoing.notificacoes.connector=smallrye-rabbitmq
mp.messaging.outgoing.notificacoes.exchange.type=direct
mp.messaging.outgoing.notificacoes.default-routing-key=agencia.change_status
mp.messaging.outgoing.notificacoes.host=localhost
mp.messaging.outgoing.notificacoes.port=5672

# Essas configurações definem o canal de saída para o Kafka, especificando o tópico remover-agencia-string e o
# serializador de valores como StringSerializer.
# Também configuramos o bootstrap.servers para apontar para o Kafka em localhost:9092.
mp.messaging.outgoing.remover-agencia-channel.connector=smallrye-kafka
mp.messaging.outgoing.remover-agencia-channel.topic=remover-agencia-avro
mp.messaging.outgoing.remover-agencia-channel.value.serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
mp.messaging.outgoing.remover-agencia-channel.auto.register.schemas=true
mp.messaging.outgoing.remover-agencia-channel.bootstrap.servers=${QUARKUS_KAFKA_HOST:localhost}:${QUARKUS_KAFKA_PORT:9092}
mp.messaging.outgoing.remover-agencia-channel.schema.registry.url=http://localhost:8081
mp.messaging.outgoing.remover-agencia-channel.value.type=br.com.alura.Agencia

quarkus.devservices.enabled=false