quarkus.http.port=8181
quarkus.http.access-log.enabled=true
quarkus.http.access-log.pattern=common

quarkus.datasource.db-kind = postgresql
quarkus.datasource.username = ${QUARKUS_DATASOURCE_USERNAME:joao}
quarkus.datasource.password = ${QUARKUS_DATASOURCE_PASSWORD:joao}
quarkus.datasource.reactive.url = postgresql://${QUARKUS_DATASOURCE_HOST:localhost}:${QUARKUS_DATASOURCE_PORT:5432}/agencia

# Teremos um conjunto de configura��es, e utilizaremos o MicroProfile, um framework baseado no Jakarta EE,
# que vem ganhando notoriedade no mundo open source e em aplica��es empresariais e em cloud. Usaremos o SmallWrite,
# que tem sinergia com o MicroProfile. Adicionamos message, referente � mensageria, que neste caso ser� RabbitMQ,
# pois � o que estamos utilizando no curso. Outgoing significa que a sa�da � o producer, ou seja, a nossa aplica��o � um producer.
# Tamb�m haver� um Income, que ser� a entrada, o Consumer, que ser� o Audit.
# Mas aqui faremos o Outgoing, que � para onde estamos enviando a mensagem.
#
# Notifica��es, ou NotificaCoins, � o nome do nosso Channel. O Channel � o canal que abrimos entre a aplica��o e o RabbitMQ.
# Quando subirmos a aplica��o, veremos que no RabbitMQ haver� esse canal, e automaticamente ele j� gera o Exchange com o nome Notifica��es.
# O Connector ser� SmallWrite RabbitMQ, que � o padr�o.
# O Exchange Type ser� Direct, ou seja,
# precisamos de um Routing Key para informar ao RabbitMQ para qual fila a mensagem deve ser enviada. Por isso,
# definimos um Default Routing Key, que ser� Ag�ncia Change Status. No RabbitMQ, ao configurar, criaremos essa Routing Key,
# vincularemos � fila, e o Rabbit saber� que deve enviar para aquela fila espec�fica.
mp.messaging.outgoing.notificacoes.connector=smallrye-rabbitmq
mp.messaging.outgoing.notificacoes.exchange.type=direct
mp.messaging.outgoing.notificacoes.default-routing-key=agencia.change_status
mp.messaging.outgoing.notificacoes.host=localhost
mp.messaging.outgoing.notificacoes.port=5672

quarkus.devservices.enabled=false